apiVersion: v1
kind: Service
metadata:
  name: bootstrap-external
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bootstrap

---

apiVersion: v1
kind: Service
metadata:
  name: ras-external
spec:
  type: NodePort
  ports:
  - name: couchdbport
    port: 5984
    protocol: TCP
    targetPort: 5984
  selector:
    app: ras

---

apiVersion: v1
kind: Service
metadata:
  name: cps-external
spec:
  type: NodePort
  ports:
  - name: etcd-client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: cps

---

apiVersion: v1
kind: Service
metadata:
  name: engine-controller-metrics-external
spec:
  type: NodePort
  ports:
  - name: metrics
    port: 9010
    protocol: TCP
    targetPort: 9010
  selector:
    app: engine-controller

---

apiVersion: v1
kind: Service
metadata:
  name: resource-monitor-metrics-external
spec:
  type: NodePort
  ports:
  - name: metrics
    port: 9010
    protocol: TCP
    targetPort: 9010
  selector:
    app: resource-monitor

---

apiVersion: v1
kind: Service
metadata:
  name: metrics-external
spec:
  type: NodePort
  ports:
  - name: metrics
    port: 9010
    protocol: TCP
    targetPort: 9010
  selector:
    app: metrics

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-service-metrics
spec:
  selector: 
    app: prometheus-server
  type: NodePort
  ports:
    - port: 8080
      targetPort: 9090 

---

apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector: 
    app: grafana-server
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000 
    