apiVersion: v1
kind: ServiceAccount
metadata:
  name: galasa-controller
imagePullSecrets:
- name: artifactory

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: galasa
imagePullSecrets:
- name: artifactory

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: galasa-admin
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - containers
  - services
  - configmaps
  - persistentvolumeclaim
  - secrets
  - "pods/log"
  - "pods/exec"
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: galasa-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: galasa-admin
subjects:
- kind: ServiceAccount
  name: galasa-controller
