apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: engine-controller
  labels:
    app: engine-controller
spec:
  replicas: 1
  template:
    metadata:
      name: engine-controller
      labels:
        app: engine-controller
    spec:
      serviceAccountName: galasa-controller
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
      - name: resource-monitor
        image: cicsts-docker-local.artifactory.swg-devops.com/galasa-boot-embedded-amd64:latest
        imagePullPolicy: Always
        command: ["java"]
        args: 
        - -jar
        - boot.jar
        - --obr
        - file:galasa.obr
        - --trace
        - --k8scontroller
        - --bootstrap
        - $(BOOTSTRAP_URI)
        env:
        - name: BOOTSTRAP_URI
          valueFrom:
            configMapKeyRef:
              name: config
              key: bootstrap
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 9010
          name: metrics
        - containerPort: 9011
          name: health
        livenessProbe:
          httpGet:
            path: /
            port: 9011
          initialDelaySeconds: 60
          periodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: engine-controller
  labels:
    app: engine-controller
spec:
  ports:
  - port: 9010
    name: metrics
  - port: 9011
    name: health
  selector:
    app: engine-controller



