apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cps-ext
spec:
  type: NodePort
  ports:
  - name: etcd-client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: {{ .Release.Name }}-cps

