apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-metrics
  labels:
    app: {{ .Release.Name }}-metrics
spec:
  replicas: 0
  template:
    metadata:
      name: {{ .Release.Name }}-metrics
      labels:
        app: {{ .Release.Name }}-metrics
    spec:
      containers:
      - name: metrics
        image: cicsts-docker-local.artifactory.swg-devops.com/galasa-boot-embedded:latest
        imagePullPolicy: Always
        command: ["java"]
        args: 
        - -jar
        - boot.jar
        - --obr
        - file:galasa.obr
        - --metricserver
        - --bootstrap
        - $(BOOTSTRAP_URI)
        env:
        - name: BOOTSTRAP_URI
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: bootstrap
        ports:
        - containerPort: 9010
          name: metrics
        - containerPort: 9011
          name: health
        livenessProbe:
          httpGet:
            path: /
            port: 9011
          initialDelaySeconds: 60
          periodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metrics
  labels:
    app: {{ .Release.Name }}-metrics
spec:
  ports:
  - port: 9010
    name: metrics
  - port: 9011
    name: health
  selector:
    app: {{ .Release.Name }}-metrics



