apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval:     15s
      evaluation_interval: 15s 

    scrape_configs:
      - job_name: 'resource-monitor'
        scrape_interval: 5s
        static_configs:
          - targets: ['{{ .Release.Name }}-resmon:9010']
            labels:
              groups: 'test'
      - job_name: 'engine-controller'
        scrape_interval: 5s
        static_configs:
          - targets: ['{{ .Release.Name }}-controller:9010']
            labels:
              groups: 'test'
      - job_name: 'metrics'
        scrape_interval: 5s
        static_configs:
          - targets: ['{{ .Release.Name }}-metrics:9010']
            labels:
              groups: 'test'
