apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ras-ext
spec:
  type: NodePort
  ports:
  - name: couchdbport
    port: 5984
    protocol: TCP
    targetPort: 5984
  selector:
    app: {{ .Release.Name }}-ras

