apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-ras
  labels:
    name: {{ .Release.Name }}-ras
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ras
  template:
    metadata:
      name: {{ .Release.Name }}-ras
      labels:
        app: {{ .Release.Name }}-ras
    spec:
      containers:
      - name: couchdb
        image: couchdb:2
        imagePullPolicy: IfNotPresent
        env:
        - name: COUCHDB_PASSWORD
          value: galasa
        - name: COUCHDB_USER
          value: galasa
        ports:
        - containerPort: 5984
          name: couchdbport
        livenessProbe:
          httpGet:
            path: /
            port: 5984
          initialDelaySeconds: 60
          periodSeconds: 60
        volumeMounts:
        - mountPath: /opt/couchdb/data
          name: data-disk
      initContainers:
      - name: couchdb-init
        image: cicsts-docker-local.artifactory.swg-devops.com/galasa-ras-couchdb-init-amd64:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /opt/couchdb/data
          name: data-disk
      nodeSelector:
        beta.kubernetes.io/arch: amd64
        platform: hdc
      volumes:
      - name: data-disk
        persistentVolumeClaim:
          claimName: claim-couchdb
  volumeClaimTemplates:
  - metadata:
      name: data-disk
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 500M
      storageClassName: hdc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ras
  labels:
    app: {{ .Release.Name }}-ras
spec:
  ports:
  - port: 5984
    name: couchdbport
  selector:
    app: {{ .Release.Name }}-ras


