apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-controller
imagePullSecrets:
- name: artifactory

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-role
rules:
- apiGroups: ["","extensions","apps"]
  resources: ["pods","deployments","replicasets","containers","services","configmaps","persistentvolumeclaim","secrets","pods/log","pods/exec"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-role
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-controller
